# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\chatwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_chat_qwidget(object):
    def setupUi(self, chat_qwidget):
        chat_qwidget.setObjectName("chat_qwidget")
        chat_qwidget.resize(800, 600)
        chat_qwidget.setMinimumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(10)
        chat_qwidget.setFont(font)
        chat_qwidget.setStyleSheet("border: none;\n"
"border-radius: 11px;")
        self.chat_qwidget_vlayout = QtWidgets.QVBoxLayout(chat_qwidget)
        self.chat_qwidget_vlayout.setContentsMargins(10, 10, 10, 10)
        self.chat_qwidget_vlayout.setSpacing(0)
        self.chat_qwidget_vlayout.setObjectName("chat_qwidget_vlayout")
        self.chat_qframe = QtWidgets.QFrame(chat_qwidget)
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(10)
        self.chat_qframe.setFont(font)
        self.chat_qframe.setStyleSheet("border:none;\n"
"border-radius: 11px;\n"
"background-color: qlineargradient(spread:pad, x1:0.124, y1:0.0454545, x2:0.711403, y2:0.46, stop:0 rgba(104, 100, 141, 255), stop:0.870647 rgba(57, 55, 77, 255));")
        self.chat_qframe.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.chat_qframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chat_qframe.setObjectName("chat_qframe")
        self.chat_qframe_layout = QtWidgets.QVBoxLayout(self.chat_qframe)
        self.chat_qframe_layout.setContentsMargins(0, 0, 0, 0)
        self.chat_qframe_layout.setSpacing(0)
        self.chat_qframe_layout.setObjectName("chat_qframe_layout")
        self.top_frame = QtWidgets.QFrame(self.chat_qframe)
        self.top_frame.setMinimumSize(QtCore.QSize(0, 30))
        self.top_frame.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(10)
        self.top_frame.setFont(font)
        self.top_frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.483, y1:0, x2:0.543, y2:1, stop:0 rgba(255, 255, 255, 25), stop:0.736318 rgba(255, 255, 255, 0));\n"
"border-bottom-right-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"border-top-right-radius: 11px;\n"
"border-top-left-radius: 11px;")
        self.top_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame.setObjectName("top_frame")
        self.top_layout = QtWidgets.QHBoxLayout(self.top_frame)
        self.top_layout.setContentsMargins(0, 0, 0, 0)
        self.top_layout.setSpacing(0)
        self.top_layout.setObjectName("top_layout")
        self.title_frame = QtWidgets.QFrame(self.top_frame)
        self.title_frame.setStyleSheet("background-color:none;")
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.title_layout = QtWidgets.QHBoxLayout(self.title_frame)
        self.title_layout.setContentsMargins(12, 0, 0, 0)
        self.title_layout.setObjectName("title_layout")
        self.title_lable = QtWidgets.QLabel(self.title_frame)
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.title_lable.setFont(font)
        self.title_lable.setStyleSheet("background-color:none;\n"
"border-radius: 0px;\n"
"color: rgb(199, 219, 232);")
        self.title_lable.setObjectName("title_lable")
        self.title_layout.addWidget(self.title_lable)
        self.top_layout.addWidget(self.title_frame)
        self.button_frame = QtWidgets.QFrame(self.top_frame)
        self.button_frame.setMaximumSize(QtCore.QSize(150, 16777215))
        self.button_frame.setStyleSheet("background-color: none;")
        self.button_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.button_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.button_frame.setObjectName("button_frame")
        self.button_layout = QtWidgets.QHBoxLayout(self.button_frame)
        self.button_layout.setContentsMargins(0, 2, 10, 0)
        self.button_layout.setSpacing(10)
        self.button_layout.setObjectName("button_layout")
        spacerItem = QtWidgets.QSpacerItem(59, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.button_layout.addItem(spacerItem)
        self.minimize_button = QtWidgets.QPushButton(self.button_frame)
        self.minimize_button.setMinimumSize(QtCore.QSize(16, 16))
        self.minimize_button.setMaximumSize(QtCore.QSize(16, 16))
        self.minimize_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(219, 222, 57);\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(199, 202, 51);\n"
"}")
        self.minimize_button.setText("")
        self.minimize_button.setObjectName("minimize_button")
        self.button_layout.addWidget(self.minimize_button)
        self.window_button = QtWidgets.QPushButton(self.button_frame)
        self.window_button.setMinimumSize(QtCore.QSize(16, 16))
        self.window_button.setMaximumSize(QtCore.QSize(16, 16))
        self.window_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(76, 225, 49);\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(72, 205, 45);\n"
"    border-radius: 8px;\n"
"}")
        self.window_button.setText("")
        self.window_button.setObjectName("window_button")
        self.button_layout.addWidget(self.window_button)
        self.exit_button = QtWidgets.QPushButton(self.button_frame)
        self.exit_button.setMinimumSize(QtCore.QSize(16, 16))
        self.exit_button.setMaximumSize(QtCore.QSize(16, 16))
        self.exit_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(225, 0, 7);\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(205, 0, 7);\n"
"}")
        self.exit_button.setText("")
        self.exit_button.setObjectName("exit_button")
        self.button_layout.addWidget(self.exit_button)
        self.top_layout.addWidget(self.button_frame)
        self.chat_qframe_layout.addWidget(self.top_frame)
        self.output_frame = QtWidgets.QFrame(self.chat_qframe)
        self.output_frame.setStyleSheet("background-color: none;")
        self.output_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.output_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.output_frame.setObjectName("output_frame")
        self.output_layout = QtWidgets.QVBoxLayout(self.output_frame)
        self.output_layout.setContentsMargins(5, 5, 5, 5)
        self.output_layout.setSpacing(0)
        self.output_layout.setObjectName("output_layout")
        self.output_tbrowser = QtWidgets.QTextBrowser(self.output_frame)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(11)
        self.output_tbrowser.setFont(font)
        self.output_tbrowser.setStyleSheet("QTextBrowser{\n"
"    background-color: rgb(86, 83, 116 , 200);\n"
"    border: 1px solid #000;\n"
"    border-color: rgba(0, 0, 0, 50);\n"
"    color: rgb(163, 219, 232);\n"
"    /*background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:2, fx:0.5, fy:0.5, stop:0.263682 rgba(93, 90, 126, 255), stop:1 rgba(58, 56, 79, 255));*/\n"
"}\n"
"QScrollBar:vertical{\n"
"    border: none;\n"
"    background-color: rgb(69, 66, 93);\n"
"    width: 13px;\n"
"    margin: 16px 0px 16px 0px;\n"
"}\n"
"QScrollBar::handle:vertical{\n"
"    background-color: rgb(110, 106, 135);\n"
"    min-heigth:30px;\n"
"    border-radius:6px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{\n"
"    background-color: rgb(103, 99, 139);\n"
"}\n"
"QScrollBar::handle:vertical:pressed{\n"
"    background-color: rgb(160, 189, 189);\n"
"}\n"
"QScrollBar::sub-line:vertical{\n"
"    border:none;\n"
"    background-color: rgb(128, 124, 158);\n"
"    height: 13px;\n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {\n"
"    background-color: rgb(103, 99, 139);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {\n"
"    background-color: rgb(160, 189, 189);\n"
"}\n"
"QScrollBar::add-line:vertical{\n"
"    border:none;\n"
"    background-color: rgb(128, 124, 158);\n"
"    height: 13px;\n"
"    border-bottom-left-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {\n"
"    background-color: rgb(103, 99, 139);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {\n"
"    background-color: rgb(160, 189, 189);\n"
"}\n"
"QScrollBar::up-arrow:vertical,QScrollBar::down-arrow:vertical{\n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-page:vertical,QScrollBar::sub-page:vertical{\n"
"    background-color: none;\n"
"}")
        self.output_tbrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.output_tbrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.output_tbrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.output_tbrowser.setObjectName("output_tbrowser")
        self.output_layout.addWidget(self.output_tbrowser)
        self.chat_qframe_layout.addWidget(self.output_frame)
        self.input_frame = QtWidgets.QFrame(self.chat_qframe)
        self.input_frame.setMinimumSize(QtCore.QSize(0, 105))
        self.input_frame.setMaximumSize(QtCore.QSize(16777215, 105))
        self.input_frame.setStyleSheet("background-color:none;")
        self.input_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.input_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_frame.setObjectName("input_frame")
        self.input_layout = QtWidgets.QHBoxLayout(self.input_frame)
        self.input_layout.setContentsMargins(5, 5, 5, 5)
        self.input_layout.setSpacing(5)
        self.input_layout.setObjectName("input_layout")
        self.input_tedit = QtWidgets.QTextEdit(self.input_frame)
        self.input_tedit.setMinimumSize(QtCore.QSize(0, 95))
        self.input_tedit.setMaximumSize(QtCore.QSize(16777215, 95))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(10)
        self.input_tedit.setFont(font)
        self.input_tedit.setStyleSheet("QTextEdit{\n"
"    border: 1px solid #000;\n"
"    border-color: rgba(0, 0, 0, 50);\n"
"    border-radius: 6px;\n"
"    background-color: rgb(93, 90, 126);\n"
"    background-color: rgb(86, 83, 116);\n"
"    color: rgb(163, 219, 232);\n"
"}\n"
"QScrollBar:vertical{\n"
"    border: none;\n"
"    background-color: rgb(69, 66, 93);\n"
"    width: 13px;\n"
"    margin: 16px 0px 16px 0px;\n"
"}\n"
"QScrollBar::handle:vertical{\n"
"    background-color: rgb(110, 106, 135);\n"
"    min-heigth:30px;\n"
"    border-radius:6px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{\n"
"    background-color: rgb(103, 99, 139);\n"
"}\n"
"QScrollBar::handle:vertical:pressed{\n"
"    background-color: rgb(160, 189, 189);\n"
"}\n"
"QScrollBar::sub-line:vertical{\n"
"    border:none;\n"
"    background-color: rgb(128, 124, 158);\n"
"    height: 13px;\n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {\n"
"    background-color: rgb(103, 99, 139);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {\n"
"    background-color: rgb(160, 189, 189);\n"
"}\n"
"QScrollBar::add-line:vertical{\n"
"    border:none;\n"
"    background-color: rgb(128, 124, 158);\n"
"    height: 13px;\n"
"    border-bottom-left-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {\n"
"    background-color: rgb(103, 99, 139);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {\n"
"    background-color: rgb(160, 189, 189);\n"
"}\n"
"QScrollBar::up-arrow:vertical,QScrollBar::down-arrow:vertical{\n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-page:vertical,QScrollBar::sub-page:vertical{\n"
"    background-color: none;\n"
"}")
        self.input_tedit.setObjectName("input_tedit")
        self.input_layout.addWidget(self.input_tedit)
        self.input_send_pbutton = QtWidgets.QPushButton(self.input_frame)
        self.input_send_pbutton.setMinimumSize(QtCore.QSize(90, 90))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_send_pbutton.setFont(font)
        self.input_send_pbutton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(92, 100, 111);\n"
"    background-color: rgb(86, 83, 116);\n"
"    color: rgb(199, 219, 232);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(74, 71, 100);\n"
"}\n"
"QPushButton:pressed{\n"
"    \n"
"    color: rgb(84, 92, 108);\n"
"    background-color: rgb(70, 77, 81);\n"
"    background-color: rgb(160, 189, 189);\n"
"}")
        self.input_send_pbutton.setObjectName("input_send_pbutton")
        self.input_layout.addWidget(self.input_send_pbutton)
        self.chat_qframe_layout.addWidget(self.input_frame)
        self.bottom_frame = QtWidgets.QFrame(self.chat_qframe)
        self.bottom_frame.setMinimumSize(QtCore.QSize(0, 25))
        self.bottom_frame.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(10)
        self.bottom_frame.setFont(font)
        self.bottom_frame.setStyleSheet("background-color: rgb(112, 108, 147,50);\n"
"border-bottom-right-radius: 11px;\n"
"border-bottom-left-radius: 11px;\n"
"border-top-right-radius: 0px;\n"
"border-top-left-radius: 0px;")
        self.bottom_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_frame.setObjectName("bottom_frame")
        self.chat_qframe_layout.addWidget(self.bottom_frame)
        self.chat_qwidget_vlayout.addWidget(self.chat_qframe)

        self.retranslateUi(chat_qwidget)
        QtCore.QMetaObject.connectSlotsByName(chat_qwidget)

    def retranslateUi(self, chat_qwidget):
        _translate = QtCore.QCoreApplication.translate
        chat_qwidget.setWindowTitle(_translate("chat_qwidget", "Form"))
        self.title_lable.setText(_translate("chat_qwidget", "Title"))
        self.input_send_pbutton.setText(_translate("chat_qwidget", "Send"))
